version: "3.5"
services:
  postgres:
    image: postgres:16-alpine
    env_file: /root/linkwarden/.env  # Absoluut pad naar je .env bestand
    restart: always
    volumes:
      - /root/linkwarden/pgdata:/var/lib/postgresql/data
  linkwarden:
    env_file: /root/linkwarden/.env  # Absoluut pad naar je .env bestand
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    restart: always
    image: ghcr.io/linkwarden/linkwarden:latest
    ports:
      - 3000:3000
    volumes:
      - /root/linkwarden/data:/data/data
    depends_on:
      - postgres